export const FIELD_TYPES = [
  "text",
  "textarea",
  "number",
  "date",
  "select",
  "checkbox",
] as const;

export type FieldType = (typeof FIELD_TYPES)[number];

export type AppValue = string | number | boolean;

/**
 * All properties are required on purpose. Besides making the local runtime
 * predictable, this shape can be represented by an OpenAI strict JSON schema.
 */
export interface FieldSpec {
  id: string;
  label: string;
  type: FieldType;
  required: boolean;
  placeholder: string;
  options: string[];
}

export interface FieldValue {
  fieldId: string;
  value: AppValue;
}

/**
 * Values are an array instead of a free-form object so generated specs can use
 * `additionalProperties: false` all the way down.
 */
export interface AppRecord {
  id: string;
  values: FieldValue[];
}

export interface AppSpec {
  schemaVersion: 1;
  title: string;
  description: string;
  entityName: string;
  entityNamePlural: string;
  layout: "table" | "cards";
  theme: {
    accent: string;
    background: string;
  };
  fields: FieldSpec[];
  features: {
    search: boolean;
    stats: boolean;
    filterField: string | null;
  };
  seedData: AppRecord[];
  acceptanceCriteria: string[];
}

/**
 * A self-contained frontend application generated by the model. Keeping the
 * first version to one HTML document lets the Studio preview and exported ZIP
 * run the exact same artifact without a build step or dependency installer.
 */
export interface WebAppArtifact {
  schemaVersion: 1;
  kind: "web_app";
  title: string;
  description: string;
  html: string;
  acceptanceCriteria: string[];
}

export interface BuildPlanStep {
  title: string;
  description: string;
}

/**
 * A model-authored, user-reviewable plan for one Web App generation. This is
 * an explicit build contract, not a representation of private chain-of-thought.
 */
export interface BuildPlan {
  schemaVersion: 1;
  kind: "web_app_plan";
  title: string;
  requestSummary: string;
  designDecisions: string[];
  interactionFlow: string[];
  implementationSteps: BuildPlanStep[];
  assumptions: string[];
  acceptanceCriteria: string[];
}

/**
 * Existing AppSpec JSON is intentionally still a valid stored artifact, so D1
 * rows and exported CRUD projects need no data migration.
 */
export type StoredArtifact = AppSpec | WebAppArtifact;

export type ProjectStatus = "draft" | "generating" | "ready" | "error";

export interface Project {
  id: string;
  name: string;
  prompt: string;
  status: ProjectStatus;
  currentVersionId: string | null;
  records: AppRecord[];
  createdAt: string;
  updatedAt: string;
}

export interface Version {
  id: string;
  projectId: string;
  number: number;
  instruction: string | null;
  spec: StoredArtifact;
  buildPlan: BuildPlan | null;
  reasoningSummary: string[];
  createdAt: string;
}

export type ValidationResult<T> =
  | { success: true; data: T }
  | { success: false; issues: ValidationIssue[] };

export interface ValidationIssue {
  path: string;
  message: string;
}
